# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# list of resource config to be applied
resources:
- frontend-deployment.yaml
- frontend-service.yaml


commonLabels:
  author: mingtong
