apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels: 
        app: web-frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: web-frontend
        image:  mingtong/web-frontend:latest
        ports:
          - name: http
            containerPort: 80
        resources:
          requests: 
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2048Mi           
