apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels: 
        app: web-backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: web-backend
        image:  mingtong/web-backend:latest
        ports:
          - name: http
            containerPort: 80
        resources:
          requests: 
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2048Mi 
        env:
          - name: STAGE
            value: $(STAGE)                      
