apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels: 
        app: backend-app
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: backend-app
        image:  mingtong/backend-app:latest
        ports:
          - name: http
            containerPort: 80
        resources:
          requests: 
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2048Mi           
