apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

# - web-frontend
resources:
- web-backend
- web-frontend
- config.yaml

images:
- name: mingtong/web-backend
  newName: 432127183358.dkr.ecr.us-east-2.amazonaws.com/mingtong/web-backend
  newTag: bd76c7437af203d0dff36c666495df0d848aebd3
- name: mingtong/web-frontend
  newName: 432127183358.dkr.ecr.us-east-2.amazonaws.com/mingtong/web-frontend
  newTag: dd32ef8cee7cc528bef9cd54ee924e172507492f

vars:
- fieldref:
    fieldPath: data.stage
  name: STAGE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dev-config
