apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all resources to
namespace: argo-demo-dev

resources:
- web-frontend
- web-backend
- config.yaml

# all with following *kustomization*
images:
- name: mingtong/web-backend
  newName: 432127183358.dkr.ecr.us-east-2.amazonaws.com/mingtong/web-backend
  newTag: 723083e85847242f1aa19b9521fad9e81a4cbd5a
- name: mingtong/web-frontend
  newName: 432127183358.dkr.ecr.us-east-2.amazonaws.com/mingtong/web-frontend
  newTag: dd32ef8cee7cc528bef9cd54ee924e172507492f

vars:
- fieldref:
    fieldPath: data.stage
  name: STAGE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dev-config
